grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 5
    verbose: 3
    n_jobs : -1
    scoring: roc_auc


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    search_param_grid:
      n_estimators :
        - 500
        - 600
        - 700
      
      criterion :
        - gini
        - entropy
      max_depth:
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
      min_samples_split:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
      min_samples_leaf:
        - 2
        - 3
        - 4
        - 5
        - 6
      min_weifght_fraction_leaf:
        - 0.0
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      max_features :
        - auto
        - log2
        - sqrt
        - None
      random_state :
        - 1965
        - 43
  model_2:
    module: xgboost
    class: XGBClassifier
    search_param_grid:
      n_estimators :
        - 500
        - 600
        - 700
      max_depth:
        - 3
        - 5
        - 7
        - 9
      learning_rate:
        - 0.01
        - 0.1
        - 0.2
        - 0.3
      eval_metric:
        - auc
        - error
        - logloss
      objective :
        - binary:logistic
        - multi:softmax
        - multi:softprob
        - binary:logistic
        - multi:softprob
      booster :
        - gbtree
        - gblinear
        - dart
      gamma :
        - 0.0
        - 0.1
        - 0.2
        - 0.3
        - 0.4
      random_state :
        - 1965
        - 43
  model_3:
    module: sklearn.linear_model
    class: LogisticRegression
    search_param_grid:
      C :
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      solver :
        - liblinear
        - newton-cg
        - lbfgs
        - saga
      random_state :
        - 1965
        - 43
  model_4:
    module: sklearn.neighbors
    class: KNeighborsClassifier
    search_param_grid:
      algorithm :
        - ball_tree
        - kd_tree
        - brute
      n_neighbors :
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
      p :
        - 1
        - 2
        - 3
        - 4
        - 10
      metric :
        - manhattan
        - euclidean
        - chebyshev
        - minkowski
      metric_params :
        - p=3
        - p=4
        - p=5
      
      random_state :
        - 1965
        - 43
  model_5:
    module: sklearn.svm
    class: SVC
    search_param_grid:
      C :
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      kernel :
        - linear
        - poly
        - rbf
        - sigmoid
        - precomputed
      degree :
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
      gamma :
        - 0.0
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      coef0 :
        - 0.0
        - 0.1
        - 0.2
        - 0.3
        - 0.4
        - 0.5
        - 0.6
        - 0.7
        - 0.8
        - 0.9
        - 1.0
      shrinking :
        - True
        - False
      probability :
        - True
        - False
      random_state :
        - 1965
        - 43
 