training_pipeline_config:
  pipeline_name: CCdefault
  artifact_dir: app_artifact

data_ingestion_config:
  data_ingestion_dir : stage00_data_ingestion
  dataset_download_url: uciml/default-of-credit-card-clients-dataset
  dataset_download_file_name : default-of-credit-card-clients-dataset.zip
  raw_data_dir: raw_data
  raw_data_file_name: UCI_Credit_Card.csv
  ingested_dir: ingested_data
  ingested_data_Train_file_name: Train.csv
  ingested_data_Test_file_name: Test.csv
  ingested_data_Train_collection_name: ingested_train
  ingested_data_Test_collection_name: ingested_test
  
data_validation_config:
  data_validation_dir: stage01_data_validation
  schema_dir: config
  schema_file_name: schema.yaml
  report_dir : report
  report_file_name: report.json
  report_page_file_name: report.html
  data_validated_test_collection_name : data_validated_test
  data_validated_train_collection_name : data_validated_train


data_transformation_config:
  data_transformation_dir: stage02_data_transformation
  transformed_dir: transformed_data
  transformed_train_dir: train
  transformed_test_dir: test
  preprocessing_dir: preprocessed
  preprocessed_object_file_name: preprocessed.pkl


model_trainer_config:
  model_trainer_dir: stage03_model_training
  trained_model_dir: trained_model
  model_report_dir : model_report
  model_file_name: model.pkl
  base_accuracy: 0.3
  model_config_dir: config
  model_config_file_name: model.yaml
 


model_evaluation_config:
  model_evaluation_dir: stage03_model_evaluation
  model_evaluation_file_name: model_evaluation.yaml

model_pusher_config:
  model_export_dir: saved_models