grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 2
    verbose: 3
    n_jobs : -1
    scoring: roc_auc


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    search_param_grid:
      n_estimators :
        - 500
        - 600
      
      criterion :
        - gini
        - entropy
      max_depth:
        - 6
        - 7
        - 8
      max_features :
        - auto
        - log2
        - sqrt
      random_state :
        - 1965
  model_2:
    module: xgboost
    class: XGBClassifier
    search_param_grid:
      n_estimators :
        - 500
        - 700
      max_depth:
        - 3
        - 5
        - 7
        - 9
      learning_rate:
        - 0.01
        - 0.1
      eval_metric:
        - auc
      booster :
        - gbtree
        - gblinear
      gamma :
        - 0.0
        - 0.1
      random_state :
        - 1965
  model_3:
    module: sklearn.linear_model
    class: LogisticRegression
    search_param_grid:
      C :
        - 0.9
        - 1.0
      solver :
        - liblinear
        - newton-cg
        - lbfgs
        - saga
      random_state :
        - 1965
  model_4:
    module: catboost
    class: CatBoostClassifier
    search_param_grid:
      n_estimators :
        - 500
        - 700
      max_depth:
        - 3
        - 5
        - 7
        - 9
      learning_rate:
        - 0.01
        - 0.1
      eval_metric:
        - AUC
      random_state :
        - 1965
      
  model_5:
    module: sklearn.svm
    class: SVC
    search_param_grid:
      C :
        - 0.4
        - 0.1  
      kernel :
        - rbf
        - sigmoid
      gamma :
        - 1.0
      coef0 :
        - 0.0
        - 0.001
      probability:
        - True
      random_state :
        - 1965
  model_6:
    module: sklearn.naive_bayes
    class: GaussianNB
    search_param_grid:
      var_smoothing :
        - 1e-09
        - 1e-08
        - 1e-07
        - 1e-06
        - 1e-05
        - 1e-04
        - 1e-03
        - 1e-02
        - 1e-01
        - 1.0
 