grid_search:
  module: sklearn.model_selection
  class: GridSearchCV
  params:
    cv: 5
    verbose: 2
    n_jobs : -1
    scoring: roc_auc


model_selection:
  model_1:
    module: sklearn.ensemble
    class: RandomForestClassifier
    search_param_grid:
      n_estimators :
        - 500
      criterion :
        - gini
        - entropy
      max_features :
        - auto
        - log2
  model_2:
    module: catboost
    class: CatBoostClassifier
    search_param_grid:
      iterations:
        - 100
        - 200
      learning_rate:
        - 0.01
        - 0.1
      depth:
        - 3
        - 5
        - 7
      eval_metric:
        - AUC
        - Accuracy
        - Precision
  model_3:
    module: xgboost
    class: XGBClassifier
    search_param_grid:
      max_depth:
        - 3
        - 5
        - 7
      learning_rate:
        - 0.01
        - 0.1
      n_estimators:
        - 100
        - 200
      eval_metric:
        - auc
        - error
        - logloss

 