columns:
  AGE: int
  BILL_AMT1: float
  BILL_AMT2: float
  BILL_AMT3: float
  BILL_AMT4: float
  BILL_AMT5: float
  BILL_AMT6: float
  EDUCATION: int
  ID: int
  LIMIT_BAL: float
  MARRIAGE: int
  PAY_0: int
  PAY_2: int
  PAY_3: int
  PAY_4: int
  PAY_5: int
  PAY_6: int
  PAY_AMT1: float
  PAY_AMT2: float
  PAY_AMT3: float
  PAY_AMT4: float
  PAY_AMT5: float
  PAY_AMT6: float
  SEX: int
  default.payment.next.month: int
columns_to_cluster:
- LIMIT_BAL
- SEX
- EDUCATION
- MARRIAGE
- AGE
- PAY_0
- PAY_2
- PAY_3
- PAY_4
- PAY_5
- PAY_6
- BILL_AMT1
- BILL_AMT2
- BILL_AMT3
- BILL_AMT4
- BILL_AMT5
- BILL_AMT6
- PAY_AMT1
- PAY_AMT2
- PAY_AMT3
- PAY_AMT4
- PAY_AMT5
- PAY_AMT6
- default.payment.next.month

target_column: default.payment.next.month
